// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udzdnevvfcrieoytzrzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkemRuZXZ2ZmNyaWVveXR6cnpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTMyNDMsImV4cCI6MjA2Mzg2OTI0M30.TGt6oeogbk2-hI8Y_sbLBAp1ymBCHQPHDDIxhw49wDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);